swagger: '2.0'
info:
  title: Text Processing API
  description: API for processing text.
  version: "1.0.0"
paths:
  /text-processing:
    post:
      summary: Process text
      description: Endpoint to process text.
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: file
          type: file
          required: true
          description: File to be processed.
      responses:
        200:
          description: A list of processed text items.
          schema:
            type: object
            properties:
              status_code:
                type: integer
              description:
                type: string
              data:
                type: array
                items:
                  type: string
        400:
          description: Error message for when no file is provided.
